### ISSUE TITLE
Why is "revision" a union?

### ISSUE THREAD

**Issue by llhotka** [netconf-wg/yang-library#13]
The type of `revision` is a union where one member is an empty string. This would IMO make sense if the `revision` leaf was mandatory. Is there any semantic difference between the following two cases?
- `revision` not present, and
- `"revision": ""`

**Comment by mbj4668** [comment]
Ladislav Lhotka notifications@github.com wrote:

> The type of `revision` is a union where one member is an empty string
> This would IMO make sense if the `revision` leaf was mandatory

It is used as a key, thus it is mandatory.

/martin

**Comment by llhotka** [comment]
OK, sorry, I missed that.
